
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'{\xc8\xce\x92I\xf49\x97\xe1l_/V\xca\x00\x10'
    
_lr_action_items = {'LPAR':([4,9,12,13,14,15,16,19,22,23,24,26,28,30,31,32,33,35,],[8,12,12,-15,-25,12,-21,-24,-18,-13,-17,-19,12,12,12,-22,-20,-23,]),'GUESS':([13,14,15,16,19,22,23,24,26,30,32,33,35,],[-15,-25,22,-21,-24,-18,-13,-17,-19,-16,-22,-20,-23,]),'GRAMMAR':([0,],[2,]),'STRING':([9,12,13,14,15,16,19,22,23,24,26,28,30,31,32,33,35,],[14,14,-15,-25,14,-21,-24,-18,-13,-17,-19,14,14,14,-22,-20,-23,]),'SEMI':([9,13,14,15,16,17,18,19,22,23,24,26,27,28,30,31,32,33,34,35,36,37,],[-16,-15,-25,-14,-21,-12,29,-24,-18,-13,-17,-19,-11,-16,-16,-16,-22,-20,-10,-23,38,-9,]),'OR':([9,12,13,14,15,16,17,19,22,23,24,26,28,30,31,32,33,34,35,],[-16,-16,-15,-25,-14,-21,28,-24,-18,-13,-17,-19,-16,-16,-16,-22,-20,28,-23,]),'COLON':([4,13,14,15,16,19,20,22,23,24,26,30,32,33,35,],[9,-15,-25,25,-21,-24,31,-18,-13,-17,-19,-16,-22,-20,-23,]),'TIMES':([13,14,15,16,19,22,23,24,26,30,32,33,35,],[-15,-25,24,-21,-24,-18,-13,-17,-19,-16,-22,-20,-23,]),'PLUS':([13,14,15,16,19,22,23,24,26,30,32,33,35,],[-15,-25,26,-21,-24,-18,-13,-17,-19,-16,-22,-20,-23,]),'RPAR':([11,12,13,14,15,16,17,19,21,22,23,24,26,27,28,30,32,33,34,35,37,],[20,-16,-15,-25,-14,-21,-12,-24,32,-18,-13,-17,-19,-11,-16,-16,-22,-20,-10,-23,-9,]),'ID':([0,2,3,6,8,9,12,13,14,15,16,19,22,23,24,25,26,28,29,30,31,32,33,35,38,],[4,6,4,4,11,19,19,-15,-25,19,-21,-24,-18,-13,-17,33,-19,19,-8,19,19,-22,-20,-23,-7,]),'IMPL':([19,],[30,]),'$end':([0,1,3,5,6,7,10,29,38,],[-4,-3,-6,0,-2,-5,-1,-8,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'__list__1':([17,34,],[27,37,]),'__list__0':([0,3,6,],[1,7,10,]),'__list__2':([9,12,15,28,30,31,],[13,13,23,13,13,13,]),'rule':([0,3,6,],[3,3,3,]),'alt_elem':([9,12,15,28,30,31,],[15,15,15,15,15,15,]),'basic_alt_elem':([9,12,15,28,30,31,],[16,16,16,16,16,16,]),'alt':([9,12,28,30,31,],[17,17,34,35,17,]),'alts':([9,12,31,],[18,21,36,]),'unit':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> unit","S'",1,None,None,None),
  ('unit -> GRAMMAR ID __list__0','unit',3,'p_unit_0','/home/arian/source/irakere/src/irakere/grammar/parser2.py',118),
  ('unit -> GRAMMAR ID','unit',2,'p_unit_1','/home/arian/source/irakere/src/irakere/grammar/parser2.py',125),
  ('unit -> __list__0','unit',1,'p_unit_2','/home/arian/source/irakere/src/irakere/grammar/parser2.py',132),
  ('unit -> <empty>','unit',0,'p_unit_3','/home/arian/source/irakere/src/irakere/grammar/parser2.py',139),
  ('__list__0 -> rule __list__0','__list__0',2,'p___list__0_4','/home/arian/source/irakere/src/irakere/grammar/parser2.py',146),
  ('__list__0 -> rule','__list__0',1,'p___list__0_5','/home/arian/source/irakere/src/irakere/grammar/parser2.py',153),
  ('rule -> ID LPAR ID RPAR COLON alts SEMI','rule',7,'p_rule_6','/home/arian/source/irakere/src/irakere/grammar/parser2.py',160),
  ('rule -> ID COLON alts SEMI','rule',4,'p_rule_7','/home/arian/source/irakere/src/irakere/grammar/parser2.py',167),
  ('__list__1 -> OR alt __list__1','__list__1',3,'p___list__1_8','/home/arian/source/irakere/src/irakere/grammar/parser2.py',174),
  ('__list__1 -> OR alt','__list__1',2,'p___list__1_9','/home/arian/source/irakere/src/irakere/grammar/parser2.py',181),
  ('alts -> alt __list__1','alts',2,'p_alts_10','/home/arian/source/irakere/src/irakere/grammar/parser2.py',188),
  ('alts -> alt','alts',1,'p_alts_11','/home/arian/source/irakere/src/irakere/grammar/parser2.py',195),
  ('__list__2 -> alt_elem __list__2','__list__2',2,'p___list__2_12','/home/arian/source/irakere/src/irakere/grammar/parser2.py',202),
  ('__list__2 -> alt_elem','__list__2',1,'p___list__2_13','/home/arian/source/irakere/src/irakere/grammar/parser2.py',209),
  ('alt -> __list__2','alt',1,'p_alt_14','/home/arian/source/irakere/src/irakere/grammar/parser2.py',216),
  ('alt -> <empty>','alt',0,'p_alt_15','/home/arian/source/irakere/src/irakere/grammar/parser2.py',223),
  ('alt_elem -> alt_elem TIMES','alt_elem',2,'p_alt_elem_16','/home/arian/source/irakere/src/irakere/grammar/parser2.py',230),
  ('alt_elem -> alt_elem GUESS','alt_elem',2,'p_alt_elem_17','/home/arian/source/irakere/src/irakere/grammar/parser2.py',237),
  ('alt_elem -> alt_elem PLUS','alt_elem',2,'p_alt_elem_18','/home/arian/source/irakere/src/irakere/grammar/parser2.py',244),
  ('alt_elem -> alt_elem COLON ID','alt_elem',3,'p_alt_elem_19','/home/arian/source/irakere/src/irakere/grammar/parser2.py',251),
  ('alt_elem -> basic_alt_elem','alt_elem',1,'p_alt_elem_20','/home/arian/source/irakere/src/irakere/grammar/parser2.py',258),
  ('basic_alt_elem -> LPAR alts RPAR','basic_alt_elem',3,'p_basic_alt_elem_21','/home/arian/source/irakere/src/irakere/grammar/parser2.py',265),
  ('basic_alt_elem -> ID IMPL alt','basic_alt_elem',3,'p_basic_alt_elem_22','/home/arian/source/irakere/src/irakere/grammar/parser2.py',272),
  ('basic_alt_elem -> ID','basic_alt_elem',1,'p_basic_alt_elem_23','/home/arian/source/irakere/src/irakere/grammar/parser2.py',279),
  ('basic_alt_elem -> STRING','basic_alt_elem',1,'p_basic_alt_elem_24','/home/arian/source/irakere/src/irakere/grammar/parser2.py',286),
]
