
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 07 23:38:59 CDT 2008
//----------------------------------------------------

package tiger.syntax;

/** CUP generated class containing symbol constants. */
public class TigerSymbol {
  /* terminals */
  public static final int LIT_9 = 5;
  public static final int IDENT = 16;
  public static final int LIT_8 = 6;
  public static final int LIT_7 = 7;
  public static final int LIT_6 = 8;
  public static final int LIT_5 = 9;
  public static final int NUMBER = 15;
  public static final int LIT_4 = 10;
  public static final int LIT_3 = 11;
  public static final int LIT_2 = 12;
  public static final int LIT_1 = 13;
  public static final int LIT_0 = 14;
  public static final int EOF = 0;
  public static final int LIT_12 = 2;
  public static final int LIT_11 = 3;
  public static final int LIT_10 = 4;
  public static final int error = 1;
}

