
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 05 14:16:31 EST 2009
//----------------------------------------------------

package org.cocuyo.dsl.entity.syntax;

/** CUP generated class containing symbol constants. */
public class EntitySymbol {
  /* terminals */
  public static final int SYMBOL = 20;
  public static final int LIT_9 = 8;
  public static final int LIT_8 = 9;
  public static final int ID = 21;
  public static final int LIT_7 = 10;
  public static final int LIT_6 = 11;
  public static final int LIT_5 = 12;
  public static final int LIT_4 = 13;
  public static final int LIT_3 = 14;
  public static final int STRING = 18;
  public static final int LIT_2 = 15;
  public static final int LIT_1 = 16;
  public static final int LIT_0 = 17;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LIT_15 = 2;
  public static final int LIT_14 = 3;
  public static final int LIT_13 = 4;
  public static final int LIT_12 = 5;
  public static final int LIT_11 = 6;
  public static final int LIT_10 = 7;
}

