
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 23 00:48:52 EDT 2008
//----------------------------------------------------

package org.cocuyo.dsl.lexer.syntax;

/** CUP generated class containing symbol constants. */
public class LexerSymbol {
  /* terminals */
  public static final int LIT_9 = 2;
  public static final int LIT_8 = 3;
  public static final int LIT_7 = 4;
  public static final int LIT_6 = 5;
  public static final int LIT_5 = 6;
  public static final int LIT_4 = 7;
  public static final int LIT_3 = 8;
  public static final int LIT_2 = 9;
  public static final int STRING_LITERAL = 14;
  public static final int LIT_1 = 10;
  public static final int LIT_0 = 11;
  public static final int EOF = 0;
  public static final int ID = 12;
  public static final int error = 1;
  public static final int LINE = 13;
}

