/* The following code was generated by JFlex 1.4.1 on 4/12/08 12:43 AM */

package org.cocuyo.dsl.textgenerator;

import org.cocuyo.parsing.cup.CupToken;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 4/12/08 12:43 AM from the specification file
 * <tt>TextGeneratorGrammar.jflex</tt>
 */
public class TextGeneratorGrammarJFlexLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    41, 41, 41, 41, 41, 41, 41, 41, 42,  4,  3,  0,  0,  2, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,  0,  0,  0,  0, 
     1,  0, 31, 44, 28,  0,  0, 32, 22, 23,  0,  0, 25, 29, 19, 37, 
    35, 34, 34, 34, 34, 34, 34, 34, 34, 34, 39,  0,  0, 24, 33, 30, 
     0, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,  0,  0,  0,  0, 40, 
    43,  6, 40,  7, 18, 10, 20,  9, 40, 11, 40,  8, 36, 12, 16, 13, 
     5, 40, 14, 17, 15, 21, 40, 38, 40, 40, 40, 26,  0, 27,  0, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
     0,  0, 40, 40, 40, 40,  0,  0,  0,  0, 40,  0,  0, 41,  0,  0, 
     0,  0,  0,  0,  0, 40,  0,  0,  0,  0, 40,  0,  0,  0,  0,  0, 
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
    40, 40, 40, 40, 40, 40, 40,  0, 40, 40, 40, 40, 40, 40, 40, 40, 
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
    40, 40, 40, 40, 40, 40, 40,  0, 40, 40, 40, 40, 40, 40, 40, 40
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\14\4\1\5\1\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\3\1\1\17\1\4\1\20\1\4\1\21\2\1\1\2"+
    "\1\4\1\22\4\4\1\23\1\24\1\25\1\26\1\27"+
    "\5\4\1\30\1\31\3\4\1\0\1\32\2\0\2\4"+
    "\2\0\2\4\1\33\1\34\1\35\6\4\1\36\1\37"+
    "\2\4\1\40\1\41\5\4\1\42\1\43\3\4\1\44"+
    "\11\4\1\45\1\46\1\4\1\47\2\4\1\50\1\51"+
    "\1\52\1\53\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\55\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276"+
    "\0\u02a3\0\u02d0\0\u02fd\0\55\0\55\0\55\0\55\0\55"+
    "\0\55\0\u010e\0\55\0\55\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\55\0\u040b\0\55\0\u0438\0\u0465\0\55\0\u0492"+
    "\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u010e\0\u010e"+
    "\0\u010e\0\u010e\0\u05cd\0\u05fa\0\u0627\0\u0654\0\u0681\0\u010e"+
    "\0\55\0\u06ae\0\u06db\0\u0708\0\u032a\0\55\0\u0357\0\u0384"+
    "\0\u0735\0\u0762\0\u078f\0\u0465\0\u07bc\0\u07e9\0\u010e\0\u010e"+
    "\0\u010e\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u010e"+
    "\0\u010e\0\u0924\0\u0951\0\u010e\0\u010e\0\u097e\0\u09ab\0\55"+
    "\0\u09d8\0\u0a05\0\u010e\0\u010e\0\u0a32\0\u0a5f\0\u0a8c\0\u010e"+
    "\0\u0ab9\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4"+
    "\0\u0c21\0\u010e\0\u010e\0\u0c4e\0\u010e\0\u0c7b\0\u0ca8\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\2\10"+
    "\1\11\1\12\1\13\1\10\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\10\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\2\1\41\1\42\1\43\1\44\1\10"+
    "\1\2\1\3\1\45\1\46\56\0\1\3\1\0\1\3"+
    "\46\0\1\3\5\0\1\47\56\0\1\10\1\50\14\10"+
    "\1\0\2\10\6\0\1\10\5\0\3\10\1\0\1\10"+
    "\1\0\3\10\7\0\14\10\1\51\1\10\1\0\2\10"+
    "\6\0\1\10\5\0\3\10\1\0\1\10\1\0\3\10"+
    "\7\0\16\10\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\5\10\1\52\10\10"+
    "\1\0\2\10\6\0\1\10\5\0\3\10\1\0\1\10"+
    "\1\0\3\10\7\0\13\10\1\53\2\10\1\0\2\10"+
    "\6\0\1\10\5\0\2\10\1\54\1\0\1\10\1\0"+
    "\3\10\7\0\7\10\1\55\3\10\1\56\1\57\1\10"+
    "\1\0\1\60\1\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\11\10\1\61\1\10\1\62"+
    "\2\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\5\10\1\63\10\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\11\10\1\64\4\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\10\10\1\65\5\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\5\10\1\66"+
    "\10\10\1\0\1\10\1\67\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\10\10\1\70\5\10"+
    "\1\0\2\10\6\0\1\10\5\0\3\10\1\0\1\10"+
    "\1\0\3\10\25\0\1\71\36\0\1\10\1\72\6\10"+
    "\1\73\5\10\1\0\1\10\1\74\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\2\0\37\75\1\76"+
    "\15\75\40\77\1\76\14\77\3\100\1\76\51\100\42\0"+
    "\2\40\16\0\6\10\1\101\7\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\11\10\1\102\4\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\16\103\1\0"+
    "\2\103\6\0\1\103\7\0\1\103\1\0\1\103\1\0"+
    "\1\103\4\0\3\104\1\47\51\104\5\0\2\10\1\105"+
    "\13\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\1\106\15\10\1\0\2\10"+
    "\6\0\1\10\5\0\3\10\1\0\1\10\1\0\3\10"+
    "\7\0\12\10\1\107\1\110\2\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\15\10\1\111\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\6\10\1\112\5\10"+
    "\1\113\1\10\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\1\114\15\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\15\10\1\115\1\0\2\10\6\0\1\10"+
    "\5\0\3\10\1\0\1\10\1\0\3\10\7\0\12\10"+
    "\1\116\3\10\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\16\10\1\0\1\10"+
    "\1\117\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\12\10\1\120\3\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\1\121\15\10\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\1\122\15\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\16\10\1\0\2\10\6\0\1\10\5\0"+
    "\2\10\1\123\1\0\1\10\1\0\3\10\7\0\11\10"+
    "\1\124\4\10\1\0\2\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\13\10\1\125\2\10"+
    "\1\0\2\10\6\0\1\10\5\0\3\10\1\0\1\10"+
    "\1\0\3\10\7\0\14\10\1\126\1\10\1\0\2\10"+
    "\6\0\1\10\5\0\3\10\1\0\1\10\1\0\3\10"+
    "\7\0\6\10\1\127\7\10\1\0\2\10\6\0\1\10"+
    "\5\0\3\10\1\0\1\10\1\0\3\10\7\0\16\103"+
    "\1\0\2\103\6\0\1\103\5\0\3\103\1\0\1\103"+
    "\1\0\3\103\1\130\6\0\3\10\1\131\12\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\5\10\1\132\10\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\16\10\1\0\1\133\1\10\6\0\1\10\5\0\3\10"+
    "\1\0\1\10\1\0\3\10\7\0\5\10\1\134\10\10"+
    "\1\0\2\10\6\0\1\10\5\0\3\10\1\0\1\10"+
    "\1\0\3\10\7\0\10\10\1\135\5\10\1\0\2\10"+
    "\6\0\1\10\5\0\3\10\1\0\1\10\1\0\3\10"+
    "\7\0\5\10\1\136\10\10\1\0\2\10\6\0\1\10"+
    "\5\0\3\10\1\0\1\10\1\0\3\10\7\0\16\10"+
    "\1\0\1\10\1\137\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\5\10\1\140\10\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\5\10\1\141\10\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\14\10\1\142\1\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\12\10\1\143"+
    "\3\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\12\10\1\144\3\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\1\10\1\145\14\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\2\10\1\146\13\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\11\10\1\147"+
    "\4\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\13\10\1\150\2\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\11\10\1\151\4\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\11\10\1\152\4\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\5\10\1\153"+
    "\10\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\5\10\1\154\10\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\5\10\1\155\10\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\4\10\1\156\11\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\12\10\1\157"+
    "\3\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\12\10\1\160\3\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\12\10\1\161\3\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\7\0"+
    "\13\10\1\162\2\10\1\0\2\10\6\0\1\10\5\0"+
    "\3\10\1\0\1\10\1\0\3\10\7\0\13\10\1\163"+
    "\2\10\1\0\2\10\6\0\1\10\5\0\3\10\1\0"+
    "\1\10\1\0\3\10\7\0\5\10\1\164\10\10\1\0"+
    "\2\10\6\0\1\10\5\0\3\10\1\0\1\10\1\0"+
    "\3\10\7\0\14\10\1\165\1\10\1\0\2\10\6\0"+
    "\1\10\5\0\3\10\1\0\1\10\1\0\3\10\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3285];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\16\1\6\11\1\1\2\11"+
    "\5\1\1\11\1\1\1\11\2\1\1\11\21\1\1\11"+
    "\3\1\1\0\1\11\2\0\2\1\2\0\23\1\1\11"+
    "\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public boolean isAtEOF()
	{
		return zzEOFDone;
	}
	/*open-other-methods*//*close-other-methods*/


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TextGeneratorGrammarJFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public TextGeneratorGrammarJFlexLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public CupToken next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { CupToken _token = new CupToken(-1, yytext(), "",yyline, yycolumn, yychar);
	_token.isBadToken(true);
	return _token;
          }
        case 46: break;
        case 26: 
          { return new CupToken(TextGeneratorGrammarSymbol.STRING_LITERAL, yytext(), "", yyline, yycolumn, 0);
          }
        case 47: break;
        case 25: 
          { return new CupToken(TextGeneratorGrammarSymbol._PTO_PTO, yytext(), "", yyline, yycolumn, 0);
          }
        case 48: break;
        case 38: 
          { return new CupToken(TextGeneratorGrammarSymbol.FALSE, yytext(), "", yyline, yycolumn, 0);
          }
        case 49: break;
        case 44: 
          { return new CupToken(TextGeneratorGrammarSymbol.PACKAGE, yytext(), "", yyline, yycolumn, 0);
          }
        case 50: break;
        case 9: 
          { return new CupToken(TextGeneratorGrammarSymbol._COMMA, yytext(), "", yyline, yycolumn, 0);
          }
        case 51: break;
        case 33: 
          { return new CupToken(TextGeneratorGrammarSymbol.FUN, yytext(), "", yyline, yycolumn, 0);
          }
        case 52: break;
        case 21: 
          { return new CupToken(TextGeneratorGrammarSymbol.IF, yytext(), "", yyline, yycolumn, 0);
          }
        case 53: break;
        case 4: 
          { return new CupToken(TextGeneratorGrammarSymbol.ID, yytext(), "", yyline, yycolumn, 0);
          }
        case 54: break;
        case 19: 
          { return new CupToken(TextGeneratorGrammarSymbol.IN, yytext(), "", yyline, yycolumn, 0);
          }
        case 55: break;
        case 31: 
          { return new CupToken(TextGeneratorGrammarSymbol.SEP, yytext(), "", yyline, yycolumn, 0);
          }
        case 56: break;
        case 7: 
          { return new CupToken(TextGeneratorGrammarSymbol._RPAR, yytext(), "", yyline, yycolumn, 0);
          }
        case 57: break;
        case 16: 
          { return new CupToken(TextGeneratorGrammarSymbol._SLASH, yytext(), "", yyline, yycolumn, 0);
          }
        case 58: break;
        case 8: 
          { return new CupToken(TextGeneratorGrammarSymbol._EQUAL, yytext(), "", yyline, yycolumn, 0);
          }
        case 59: break;
        case 29: 
          { return new CupToken(TextGeneratorGrammarSymbol.END, yytext(), "", yyline, yycolumn, 0);
          }
        case 60: break;
        case 17: 
          { return new CupToken(TextGeneratorGrammarSymbol._DPTO, yytext(), "", yyline, yycolumn, 0);
          }
        case 61: break;
        case 43: 
          { return new CupToken(TextGeneratorGrammarSymbol.LISTEN, yytext(), "", yyline, yycolumn, 0);
          }
        case 62: break;
        case 10: 
          { return new CupToken(TextGeneratorGrammarSymbol._LKEY, yytext(), "", yyline, yycolumn, 0);
          }
        case 63: break;
        case 34: 
          { return new CupToken(TextGeneratorGrammarSymbol.ELIF, yytext(), "", yyline, yycolumn, 0);
          }
        case 64: break;
        case 28: 
          { return new CupToken(TextGeneratorGrammarSymbol.GEN, yytext(), "", yyline, yycolumn, 0);
          }
        case 65: break;
        case 45: 
          { return new CupToken(TextGeneratorGrammarSymbol.ASPECTS, yytext(), "", yyline, yycolumn, 0);
          }
        case 66: break;
        case 13: 
          { return new CupToken(TextGeneratorGrammarSymbol._MINUS, yytext(), "", yyline, yycolumn, 0);
          }
        case 67: break;
        case 35: 
          { return new CupToken(TextGeneratorGrammarSymbol.ELSE, yytext(), "", yyline, yycolumn, 0);
          }
        case 68: break;
        case 27: 
          { return new CupToken(TextGeneratorGrammarSymbol.GET, yytext(), "", yyline, yycolumn, 0);
          }
        case 69: break;
        case 36: 
          { return new CupToken(TextGeneratorGrammarSymbol.TRUE, yytext(), "", yyline, yycolumn, 0);
          }
        case 70: break;
        case 32: 
          { return new CupToken(TextGeneratorGrammarSymbol.FOR, yytext(), "", yyline, yycolumn, 0);
          }
        case 71: break;
        case 41: 
          { return new CupToken(TextGeneratorGrammarSymbol.INDENT, yytext(), "", yyline, yycolumn, 0);
          }
        case 72: break;
        case 15: 
          { return new CupToken(TextGeneratorGrammarSymbol.NUMBER_LITERAL, yytext(), "", yyline, yycolumn, 0);
          }
        case 73: break;
        case 39: 
          { return new CupToken(TextGeneratorGrammarSymbol.WRITE, yytext(), "", yyline, yycolumn, 0);
          }
        case 74: break;
        case 3: 
          { yycolumn = yycolumn - yycolumn%4 + 3;
          }
        case 75: break;
        case 5: 
          { return new CupToken(TextGeneratorGrammarSymbol._PTO, yytext(), "", yyline, yycolumn, 0);
          }
        case 76: break;
        case 18: 
          { return new CupToken(TextGeneratorGrammarSymbol.AS, yytext(), "", yyline, yycolumn, 0);
          }
        case 77: break;
        case 37: 
          { return new CupToken(TextGeneratorGrammarSymbol.SUPER, yytext(), "", yyline, yycolumn, 0);
          }
        case 78: break;
        case 20: 
          { return new CupToken(TextGeneratorGrammarSymbol.IS, yytext(), "", yyline, yycolumn, 0);
          }
        case 79: break;
        case 23: 
          { return new CupToken(TextGeneratorGrammarSymbol.ON, yytext(), "", yyline, yycolumn, 0);
          }
        case 80: break;
        case 22: 
          { return new CupToken(TextGeneratorGrammarSymbol.OR, yytext(), "", yyline, yycolumn, 0);
          }
        case 81: break;
        case 42: 
          { return new CupToken(TextGeneratorGrammarSymbol.RETURN, yytext(), "", yyline, yycolumn, 0);
          }
        case 82: break;
        case 40: 
          { return new CupToken(TextGeneratorGrammarSymbol.IMPORT, yytext(), "", yyline, yycolumn, 0);
          }
        case 83: break;
        case 6: 
          { return new CupToken(TextGeneratorGrammarSymbol._LPAR, yytext(), "", yyline, yycolumn, 0);
          }
        case 84: break;
        case 30: 
          { return new CupToken(TextGeneratorGrammarSymbol.NOT, yytext(), "", yyline, yycolumn, 0);
          }
        case 85: break;
        case 11: 
          { return new CupToken(TextGeneratorGrammarSymbol._RKEY, yytext(), "", yyline, yycolumn, 0);
          }
        case 86: break;
        case 14: 
          { return new CupToken(TextGeneratorGrammarSymbol._QUERY, yytext(), "", yyline, yycolumn, 0);
          }
        case 87: break;
        case 12: 
          { return new CupToken(TextGeneratorGrammarSymbol._MONEY, yytext(), "", yyline, yycolumn, 0);
          }
        case 88: break;
        case 24: 
          { return new CupToken(TextGeneratorGrammarSymbol.DO, yytext(), "", yyline, yycolumn, 0);
          }
        case 89: break;
        case 2: 
          { 
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return new CupToken(TextGeneratorGrammarSymbol.EOF, yytext(), "", yyline, yycolumn, 0, true);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
