
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 12 00:43:16 EDT 2008
//----------------------------------------------------

package org.cocuyo.dsl.textgenerator;

/** CUP generated class containing symbol constants. */
public class TextGeneratorGrammarSymbol {
  /* terminals */
  public static final int SEP = 41;
  public static final int STRING_LITERAL = 24;
  public static final int _LKEY = 17;
  public static final int _QUERY = 23;
  public static final int _SLASH = 28;
  public static final int NUMBER_LITERAL = 25;
  public static final int FOR = 40;
  public static final int LISTEN = 32;
  public static final int WRITE = 30;
  public static final int _MINUS = 20;
  public static final int NOT = 39;
  public static final int IS = 5;
  public static final int _RPAR = 13;
  public static final int FUN = 11;
  public static final int OR = 35;
  public static final int IN = 29;
  public static final int GET = 33;
  public static final int ASPECTS = 31;
  public static final int ON = 9;
  public static final int _COMMA = 16;
  public static final int _DPTO = 42;
  public static final int IF = 36;
  public static final int GEN = 4;
  public static final int ID = 43;
  public static final int EOF = 0;
  public static final int _PTO = 7;
  public static final int RETURN = 14;
  public static final int _RKEY = 18;
  public static final int TRUE = 26;
  public static final int SUPER = 22;
  public static final int error = 1;
  public static final int _EQUAL = 15;
  public static final int IMPORT = 3;
  public static final int ELSE = 37;
  public static final int PACKAGE = 2;
  public static final int END = 6;
  public static final int _LPAR = 12;
  public static final int _PTO_PTO = 34;
  public static final int _MONEY = 19;
  public static final int FALSE = 27;
  public static final int AS = 8;
  public static final int INDENT = 21;
  public static final int ELIF = 38;
  public static final int DO = 10;
}

