
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 12 13:44:32 EDT 2008
//----------------------------------------------------

package org.cocuyo.dsl.grammar;

/** CUP generated class containing symbol constants. */
public class CocuyoGrammarSymbol {
  /* terminals */
  public static final int IMPORT = 3;
  public static final int _LKEY = 9;
  public static final int _RCOR = 15;
  public static final int _MUL = 24;
  public static final int _LCOR = 14;
  public static final int _MINUS = 26;
  public static final int END = 18;
  public static final int _PTOCOMMA = 20;
  public static final int _PTO = 4;
  public static final int _MINUS_RANG = 19;
  public static final int ID = 27;
  public static final int _QUERY = 25;
  public static final int GRAMMAR = 17;
  public static final int _EXCLAM = 11;
  public static final int _RPAR = 7;
  public static final int STRING_LITERAL = 13;
  public static final int EOF = 0;
  public static final int _LPAR = 6;
  public static final int NUMBER_LITERAL = 12;
  public static final int _OR = 21;
  public static final int error = 1;
  public static final int _EQUAL = 8;
  public static final int _ADD = 23;
  public static final int PACKAGE = 2;
  public static final int _EQUAL_RANG = 22;
  public static final int _AT = 5;
  public static final int _RKEY = 10;
  public static final int _DPTO = 16;
}

