
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 12 13:08:10 EDT 2008
//----------------------------------------------------

package org.cocuyo.dsl._native.syntax;

/** CUP generated class containing symbol constants. */
public class NativeSymbol {
  /* terminals */
  public static final int ID = 7;
  public static final int TEXT = 6;
  public static final int error = 1;
  public static final int LIT_3 = 2;
  public static final int LIT_2 = 3;
  public static final int LIT_1 = 4;
  public static final int LIT_0 = 5;
  public static final int EOF = 0;
}

