
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 12 13:08:10 EDT 2008
//----------------------------------------------------

package org.cocuyo.dsl._native.syntax;


/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Aug 12 13:08:10 EDT 2008
  */
public class NativeCupParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public NativeCupParser() {super();}

  /** Constructor which sets the default scanner. */
  public NativeCupParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public NativeCupParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\010\000\002\002\004\000\002\002" +
    "\004\000\002\002\006\000\002\002\002\000\002\003\005" +
    "\000\002\003\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\010\002\ufffd\006\005\007\006\001\002\000" +
    "\004\002\023\001\002\000\004\011\007\001\002\000\004" +
    "\011\007\001\002\000\012\002\ufffa\004\ufffa\005\ufffa\006" +
    "\ufffa\001\002\000\006\002\uffff\006\014\001\002\000\010" +
    "\002\ufffb\004\012\006\ufffb\001\002\000\004\011\007\001" +
    "\002\000\006\002\ufffc\006\ufffc\001\002\000\004\011\007" +
    "\001\002\000\004\005\016\001\002\000\004\010\017\001" +
    "\002\000\004\002\001\001\002\000\004\005\021\001\002" +
    "\000\004\010\022\001\002\000\004\002\ufffe\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\021\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\004\017\001\001\000\006\003\007\004\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\003\012\004\010\001\001\000\002\001\001\000\004" +
    "\004\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$NativeCupParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$NativeCupParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$NativeCupParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
  
    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }
}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$NativeCupParser$actions {
  private final NativeCupParser parser;

  /** Constructor */
  CUP$NativeCupParser$actions(NativeCupParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$NativeCupParser$do_action(
    int                        CUP$NativeCupParser$act_num,
    java_cup.runtime.lr_parser CUP$NativeCupParser$parser,
    java.util.Stack            CUP$NativeCupParser$stack,
    int                        CUP$NativeCupParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$NativeCupParser$result;

      /* select the action based on the action number */
      switch (CUP$NativeCupParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Id ::= ID 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("Id",2, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Name ::= Id 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("Name",1, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Name ::= Id LIT_3 Name 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("Name",1, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-2)), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CompileUnit ::= 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("CompileUnit",0, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // CompileUnit ::= LIT_1 Id LIT_2 TEXT 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("CompileUnit",0, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-3)), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CompileUnit ::= LIT_0 Name 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("CompileUnit",0, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-1)), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= CompileUnit EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-1)).value;
		RESULT = start_val;
              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-1)), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$NativeCupParser$parser.done_parsing();
          return CUP$NativeCupParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // CompileUnit ::= LIT_0 Name LIT_1 Id LIT_2 TEXT 
            {
              Object RESULT =null;

              CUP$NativeCupParser$result = parser.getSymbolFactory().newSymbol("CompileUnit",0, ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.elementAt(CUP$NativeCupParser$top-5)), ((java_cup.runtime.Symbol)CUP$NativeCupParser$stack.peek()), RESULT);
            }
          return CUP$NativeCupParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

